In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
# Load the dataset
df = pd.read_csv("../data/smartcare_ai_dataset_1000.csv")

# Load the data dictionary
data_dictionary = pd.read_csv("../data/smartcare_ai_dataset_data_dictionary.csv")

print("Dataset loaded successfully")

Dataset loaded successfully

In [3]:
# Display the first five rows
df.head()

   record_id patient_id  age  gender blood_group        department     diagnosis appointment_date  waiting_days  previous_appointments  missed_previous_appointments appointment_status  admitted room_type  length_of_stay_days  previous_admissions  systolic_bp  diastolic_bp  blood_sugar_mg_dl  cholesterol_mg_dl   bmi  lab_tests_count  treatments_count  consultation_fee_lkr  room_charge_lkr  lab_charge_lkr  medicine_charge_lkr  total_bill_lkr payment_status payment_method  no_show  readmitted_30_days disease_risk_level
0          1     P10001   53    Male          A-  General Medicine      Migraine       2025-04-10            10                      1                             0          Completed         0       NaN                    0                    1          127            75                117                211  26.1                0                 3                  2000                0               0                11596           13596           Paid      Insurance        0                   0               High
1          2     P10002   26    Male          B-  General Medicine      Diabetes       2025-05-15             2                      3                             1          Completed         0       NaN                    0                    0          130            73                136                173  32.8                0                 1                  2000                0               0                 3652            5652           Paid      Insurance        0                   0             Medium
2          3     P10003   22    Male          B+       Orthopedics     Back Pain       2025-07-09            22                      7                             1            No-Show         0       NaN                    0                    1          141            64                 90                176  29.4                1                 0                  2500                0            1200                 2562            6262         Unpaid      Insurance        1                   0             Medium
3          4     P10004   44  Female         AB-        Cardiology        Asthma       2025-10-16            16                      1                             0          Completed         0       NaN                    0                    0          124            82                126                189  24.9                2                 1                  2000                0            5000                10262           17262           Paid         Online        0                   0             Medium
4          5     P10005   51  Female          O+         Neurology  Hypertension       2025-12-18            12                      4                             0          Scheduled         0       NaN                    0                    1          119            81                 65                195  27.0                2                 0                  4000                0            6000                10414           20414           Paid           Cash        0                   0             Medium

In [4]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     1000 non-null   int64
 1   patient_id                    1000 non-null   str
 2   age                           1000 non-null   int64
 3   gender                        1000 non-null   str
 4   blood_group                   1000 non-null   str
 5   department                    1000 non-null   str
 6   diagnosis                     1000 non-null   str
 7   appointment_date              1000 non-null   str
 8   waiting_days                  1000 non-null   int64
 9   previous_appointments         1000 non-null   int64
 10  missed_previous_appointments  1000 non-null   int64
 11  appointment_status            1000 non-null   str
 12  admitted                      1000 non-null   int64
 13  room_type                     94 non-null     str
 14  length_of_stay_days           1000 non-null   int64
 15  previous_admissions           1000 non-null   int64
 16  systolic_bp                   1000 non-null   int64
 17  diastolic_bp                  1000 non-null   int64
 18  blood_sugar_mg_dl             1000 non-null   int64
 19  cholesterol_mg_dl             1000 non-null   int64
 20  bmi                           1000 non-null   float64
 21  lab_tests_count               1000 non-null   int64
 22  treatments_count              1000 non-null   int64
 23  consultation_fee_lkr          1000 non-null   int64
 24  room_charge_lkr               1000 non-null   int64
 25  lab_charge_lkr                1000 non-null   int64
 26  medicine_charge_lkr           1000 non-null   int64
 27  total_bill_lkr                1000 non-null   int64
 28  payment_status                1000 non-null   str
 29  payment_method                1000 non-null   str
 30  no_show                       1000 non-null   int64
 31  readmitted_30_days            1000 non-null   int64
 32  disease_risk_level            1000 non-null   str
dtypes: float64(1), int64(21), str(11)
memory usage: 325.9 KB

In [5]:
df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     1000 non-null   int64
 1   patient_id                    1000 non-null   str
 2   age                           1000 non-null   int64
 3   gender                        1000 non-null   str
 4   blood_group                   1000 non-null   str
 5   department                    1000 non-null   str
 6   diagnosis                     1000 non-null   str
 7   appointment_date              1000 non-null   str
 8   waiting_days                  1000 non-null   int64
 9   previous_appointments         1000 non-null   int64
 10  missed_previous_appointments  1000 non-null   int64
 11  appointment_status            1000 non-null   str
 12  admitted                      1000 non-null   int64
 13  room_type                     94 non-null     str
 14  length_of_stay_days           1000 non-null   int64
 15  previous_admissions           1000 non-null   int64
 16  systolic_bp                   1000 non-null   int64
 17  diastolic_bp                  1000 non-null   int64
 18  blood_sugar_mg_dl             1000 non-null   int64
 19  cholesterol_mg_dl             1000 non-null   int64
 20  bmi                           1000 non-null   float64
 21  lab_tests_count               1000 non-null   int64
 22  treatments_count              1000 non-null   int64
 23  consultation_fee_lkr          1000 non-null   int64
 24  room_charge_lkr               1000 non-null   int64
 25  lab_charge_lkr                1000 non-null   int64
 26  medicine_charge_lkr           1000 non-null   int64
 27  total_bill_lkr                1000 non-null   int64
 28  payment_status                1000 non-null   str
 29  payment_method                1000 non-null   str
 30  no_show                       1000 non-null   int64
 31  readmitted_30_days            1000 non-null   int64
 32  disease_risk_level            1000 non-null   str
dtypes: float64(1), int64(21), str(11)
memory usage: 325.9 KB

In [6]:
df.columns

Index(['record_id', 'patient_id', 'age', 'gender', 'blood_group', 'department', 'diagnosis', 'appointment_date', 'waiting_days', 'previous_appointments', 'missed_previous_appointments', 'appointment_status', 'admitted', 'room_type', 'length_of_stay_days', 'previous_admissions', 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl', 'cholesterol_mg_dl', 'bmi', 'lab_tests_count', 'treatments_count', 'consultation_fee_lkr', 'room_charge_lkr', 'lab_charge_lkr', 'medicine_charge_lkr', 'total_bill_lkr', 'payment_status', 'payment_method', 'no_show', 'readmitted_30_days', 'disease_risk_level'], dtype='str')

In [7]:
list(df.columns)

['record_id',
 'patient_id',
 'age',
 'gender',
 'blood_group',
 'department',
 'diagnosis',
 'appointment_date',
 'waiting_days',
 'previous_appointments',
 'missed_previous_appointments',
 'appointment_status',
 'admitted',
 'room_type',
 'length_of_stay_days',
 'previous_admissions',
 'systolic_bp',
 'diastolic_bp',
 'blood_sugar_mg_dl',
 'cholesterol_mg_dl',
 'bmi',
 'lab_tests_count',
 'treatments_count',
 'consultation_fee_lkr',
 'room_charge_lkr',
 'lab_charge_lkr',
 'medicine_charge_lkr',
 'total_bill_lkr',
 'payment_status',
 'payment_method',
 'no_show',
 'readmitted_30_days',
 'disease_risk_level']

In [8]:
# Display all column names
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

1. record_id
2. patient_id
3. age
4. gender
5. blood_group
6. department
7. diagnosis
8. appointment_date
9. waiting_days
10. previous_appointments
11. missed_previous_appointments
12. appointment_status
13. admitted
14. room_type
15. length_of_stay_days
16. previous_admissions
17. systolic_bp
18. diastolic_bp
19. blood_sugar_mg_dl
20. cholesterol_mg_dl
21. bmi
22. lab_tests_count
23. treatments_count
24. consultation_fee_lkr
25. room_charge_lkr
26. lab_charge_lkr
27. medicine_charge_lkr
28. total_bill_lkr
29. payment_status
30. payment_method
31. no_show
32. readmitted_30_days
33. disease_risk_level

In [9]:
data_dictionary

                          Column                                        Description
0                      record_id                              Unique row identifier
1                     patient_id                       Synthetic patient identifier
2                            age                               Patient age in years
3                         gender                                     Patient gender
4                    blood_group                                Patient blood group
5                     department                                Hospital department
6                      diagnosis                         Primary diagnosis category
7               appointment_date                                   Appointment date
8                   waiting_days     Number of days between booking and appointment
9          previous_appointments                    Number of previous appointments
10  missed_previous_appointments           Number of previously missed appointments
11            appointment_status        Completed, Cancelled, No-Show, or Scheduled
12                      admitted          Whether patient was admitted: 1=Yes, 0=No
13                     room_type           None, General Ward, Private Room, or ICU
14           length_of_stay_days                     Hospital stay duration in days
15           previous_admissions                      Number of previous admissions
16                   systolic_bp                  Synthetic systolic blood pressure
17                  diastolic_bp                 Synthetic diastolic blood pressure
18             blood_sugar_mg_dl                  Synthetic blood sugar measurement
19             cholesterol_mg_dl                  Synthetic cholesterol measurement
20                           bmi                          Synthetic body mass index
21               lab_tests_count                                Number of lab tests
22              treatments_count                               Number of treatments
23          consultation_fee_lkr                            Consultation fee in LKR
24               room_charge_lkr                                Room charges in LKR
25                lab_charge_lkr                                 Lab charges in LKR
26           medicine_charge_lkr                            Medicine charges in LKR
27                total_bill_lkr                                  Total bill in LKR
28                payment_status                    Paid, Unpaid, or Partially Paid
29                payment_method                   Cash, Card, Online, or Insurance
30                       no_show  AI target for appointment no-show prediction: ...
31            readmitted_30_days  AI target for readmission prediction: 1=Readmi...
32            disease_risk_level  AI target for disease risk prediction: Low, Me...

In [10]:
data_dictionary.head(50)

                          Column                                        Description
0                      record_id                              Unique row identifier
1                     patient_id                       Synthetic patient identifier
2                            age                               Patient age in years
3                         gender                                     Patient gender
4                    blood_group                                Patient blood group
5                     department                                Hospital department
6                      diagnosis                         Primary diagnosis category
7               appointment_date                                   Appointment date
8                   waiting_days     Number of days between booking and appointment
9          previous_appointments                    Number of previous appointments
10  missed_previous_appointments           Number of previously missed appointments
11            appointment_status        Completed, Cancelled, No-Show, or Scheduled
12                      admitted          Whether patient was admitted: 1=Yes, 0=No
13                     room_type           None, General Ward, Private Room, or ICU
14           length_of_stay_days                     Hospital stay duration in days
15           previous_admissions                      Number of previous admissions
16                   systolic_bp                  Synthetic systolic blood pressure
17                  diastolic_bp                 Synthetic diastolic blood pressure
18             blood_sugar_mg_dl                  Synthetic blood sugar measurement
19             cholesterol_mg_dl                  Synthetic cholesterol measurement
20                           bmi                          Synthetic body mass index
21               lab_tests_count                                Number of lab tests
22              treatments_count                               Number of treatments
23          consultation_fee_lkr                            Consultation fee in LKR
24               room_charge_lkr                                Room charges in LKR
25                lab_charge_lkr                                 Lab charges in LKR
26           medicine_charge_lkr                            Medicine charges in LKR
27                total_bill_lkr                                  Total bill in LKR
28                payment_status                    Paid, Unpaid, or Partially Paid
29                payment_method                   Cash, Card, Online, or Insurance
30                       no_show  AI target for appointment no-show prediction: ...
31            readmitted_30_days  AI target for readmission prediction: 1=Readmi...
32            disease_risk_level  AI target for disease risk prediction: Low, Me...

In [11]:
# Check missing values
df.isnull().sum()

record_id                         0
patient_id                        0
age                               0
gender                            0
blood_group                       0
department                        0
diagnosis                         0
appointment_date                  0
waiting_days                      0
previous_appointments             0
missed_previous_appointments      0
appointment_status                0
admitted                          0
room_type                       906
length_of_stay_days               0
previous_admissions               0
systolic_bp                       0
diastolic_bp                      0
blood_sugar_mg_dl                 0
cholesterol_mg_dl                 0
bmi                               0
lab_tests_count                   0
treatments_count                  0
consultation_fee_lkr              0
room_charge_lkr                   0
lab_charge_lkr                    0
medicine_charge_lkr               0
total_bill_lkr                    0
payment_status                    0
payment_method                    0
no_show                           0
readmitted_30_days                0
disease_risk_level                0
dtype: int64

In [12]:
# Check duplicate records
df.duplicated().sum()

np.int64(0)

In [13]:
# Missing value percentage
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing[missing["Missing Values"] > 0]

           Missing Values  Percentage
room_type             906        90.6

In [14]:
# Count unique values
df.nunique()

record_id                       1000
patient_id                      1000
age                               88
gender                             2
blood_group                        8
department                         7
diagnosis                         10
appointment_date                 339
waiting_days                      45
previous_appointments             10
missed_previous_appointments       5
appointment_status                 4
admitted                           2
room_type                          3
length_of_stay_days               10
previous_admissions                6
systolic_bp                       83
diastolic_bp                      58
blood_sugar_mg_dl                120
cholesterol_mg_dl                172
bmi                              197
lab_tests_count                   11
treatments_count                  11
consultation_fee_lkr               6
room_charge_lkr                   22
lab_charge_lkr                    29
medicine_charge_lkr              966
total_bill_lkr                   981
payment_status                     3
payment_method                     4
no_show                            2
readmitted_30_days                 2
disease_risk_level                 3
dtype: int64